manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: urob
      url-base: https://github.com/urob
    - name: blueshaedow
      url-base: https://github.com/blueshaedow

    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  
  projects:
    # official ZMK 
    #- name: zmk
    #  remote: zmkfirmware
    #  revision: main
    #  import: app/west.yml

    # own branch
    #- name: zmk
    #  remote: blueshaedow
    #  revision: main
    #  import: app/west.yml

    # urob's branch
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml

  self:
    path: config
